version: 2.1

orbs:
  android: circleci/android@3.1.0

jobs:
  build:
    docker:
      - image: cimg/android:2025.02
    environment:
      GRADLE_VERSION: 8.9
      GRADLE_HOME: ~/gradle

    steps:
      - checkout

      - restore_cache:
          key: android-orb-v1-{{ checksum "app/build.gradle.kts" }}

      - run:
          name: Install Gradle 8.9
          command: |
            mkdir -p $GRADLE_HOME
            wget -q https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -O /tmp/gradle.zip
            unzip -qo /tmp/gradle.zip -d $GRADLE_HOME
            echo "export PATH=$GRADLE_HOME/gradle-${GRADLE_VERSION}/bin:\$PATH" >> $BASH_ENV
            source $BASH_ENV
            gradle -v

      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          key: android-orb-v1-{{ checksum "app/build.gradle.kts" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.android/cache

      - run:
          name: Run Build
          command: ./gradlew build

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: artifact-file
    executor: